### ISSUE TITLE
Getting nondeterminisitic results for find & union

### ISSUE THREAD

**Issue by adamhusar** [wjakob/dset#2]
Hello,
thank you very much for giving this code out, I was trying to use it, however, I am getting nondeterministic results (I cannot share my code unfortunately). 
What I would like to ask if this code is known to be correct, this would mean that there is some problem on my side.  (there is not any information on how this code was validated)
Thank you

**Comment by wjakob** [comment]
This code has never been tested on machines with a weak memory model (ARM/AArch64), so it's possible that there might be problems on such platforms.

**Comment by adamhusar** [comment]
Thank you very much for your answer. I think my confusion originated in checking the 'rank' values, which don't have to be deterministic (at least as I understood it). I went in the end with a direct rewrite of the article's implementation. So, I am closing this issue. Thank you
